### ISSUE TITLE
Libro de hechizos.

### ISSUE THREAD

**Issue by rgonzalezt** [JulianMartinez2797/tpObjetosEntrega1#10]
¿Qué pasa si el libro de hechizos sigue siendo un WKO y hay varios personajes que tengan uno?
¿Qué pasa si un personaje agrega un hechizo a ese libro, con respecto a los otros personajes?

**Comment by Federicobunader** [comment]
Perdon por la demora , si el libro de hechizos seria un Wko, cuando un personaje modifique el libro, todos los personajes que tengan al libro van a tener el nuevo hechizo. Por lo que esto no tendria sentido , ya que no todos los personajes tendran que tener el mismo libro de hechizos con los mismos poderes.
