### ISSUE TITLE
Poder de hechizo de los logos

### ISSUE THREAD

**Issue by rgonzalezt** [JulianMartinez2797/tpObjetosEntrega1#8]
Ahora están calculando al poder de hechizo de los logos como la cantidad de letras del nombre que tenga el hechizo cuando el enunciado dice que _el poder de hechicería es un múltiplo de la cantidad de letras de su nombre, donde el valor por el cual se multiplica puede variar de hechizo en hechizo. La forma de saber si es poderoso sigue siendo si su poder es mayor a 15._

**Comment by Federicobunader** [comment]
Poder de hechizo de Logo arreglado
