### ISSUE TITLE
Testear cosas donde debe darnos falso.

### ISSUE THREAD

**Issue by rgonzalezt** [JulianMartinez2797/tpObjetosEntrega1#9]
Si queres testear que va a dar verdadero usamos that: `assert.that(expresión)`.
Ahora, si queremos testar algo que va a dar falso, no usamos that y negamos la expresión. Para esos casos tenemos `assert.notThat(expresión)`.
Arreglen los tests que tienen esa forma.

**Comment by Federicobunader** [comment]
Tests arreglados
